@startuml
!theme plain
autonumber
skinparam boxPadding 10

box "External & Edge" #GhostWhite
    participant "App / Canais" as App
    participant "API Gateway" as GW
end box

box "Business Layer (EKS)" #AliceBlue
    participant "Worker Limit Management" as SVC
    participant "Worker Authorize balance" as Proxy
    participant "Motor de Risco\n(SaaS)" as Risk
end box

box "State & Data" #Lavender
    database "Redis\n(State/Idemp)" as Redis
    database "DynamoDB\n(Ledger)" as Dynamo
end box

box "Integration & Resilience" #Ivory
    queue "SQS FIFO\n(Main Queue)" as SQS
    participant "Legacy Worker\n(ACL)" as Worker
    database "MF/Open\n(Legacy)" as Legacy
    queue "DLQ\n(Manual/Retry)" as DLQ
end box

box "Notifications" #Cornsilk
    participant "SNS / Push" as Push
end box

== Fluxo de Ajuste de Limite (Síncrono para o Cliente) e fase de Validação == 

App -> GW : POST /v1/limits (Idempotency-Key) R$ 1,00
GW -> SVC : Request Validated R$ 2,00

SVC -> Redis : SETNX (Key) / Lock
note left: Evita cliques duplos\nnos 10M de acessos

SVC -> Risk : Consultar Política de Crédito
Risk --> SVC : Aprovado (Score OK)

SVC -> Dynamo : Put Item (Novo Limite R$ 2,00 / PENDING)
SVC -> Redis : UPDATE (Saldo Projetado)

Redis -> Proxy : Limite Atualizado para autorizacao

SVC -> Push : Trigger "Ajuste em Processamento"
SVC --> GW : 201 Created
GW --> App : Confirmação na Tela (< 50ms)

== Fluxo de Sincronização (Assíncrono / Event-Driven(Resiliencia)) ==

Dynamo -> SQS : DynamoDB Stream Event\n(LAMBDA)
activate SQS

SQS -> Worker : Trigger Message
activate Worker

Worker -> Legacy : Update Legacy (800ms)
note right: Conexão Híbrida\n(Direct Connect)

alt Sucesso no Legado
    Legacy --> Worker : 200 OK
    Worker -> Dynamo : Update Status (COMPLETED)
    Worker -> Push : Trigger "Limite Confirmado"
else Falha no Legado (Timeout/Indisponível)
    Legacy --x Worker : Error / Timeout
    Worker -> SQS : Retentativa Automática (Exponential Backoff)
    note right: O cliente não é afetado,\no limite continua no Redis.
else Erro Fatal (Negócio/Dados)
    Worker -> DLQ : Move para Dead Letter Queue
    Worker -> Dynamo : Update Status (ERROR_MANUAL_REVIEW)
end

deactivate Worker
deactivate SQS

== Fluxo de Autorização (Paralelo) ==

App -> Proxy : Realizar Compra (Cartão)
Proxy -> Redis : GET Projected_Balance
Redis --> Proxy : R$ 2,00
Proxy --> App : Compra Autorizada (Real-time)

@enduml
